site_name: Genshin Lore Docs
site_url: https://wolf0905.github.io/genshin-lore-doc/
theme:
  name: material
  custom_dir: overrides
  features:
   - navigation.tabs
   - navigation.tabs.sticky
   - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
nav:
  - 'Home': 'index.md'
  - 'Books':
    - 'books/index.md'
    - 'Mondstadt':
      - 'books/Mondstadt/Of_Mountains_and_Seas.md'
      - 'books/Mondstadt/1000_Years_of_Loneliness.md'
      - 'books/Mondstadt/A_Drunkards_Tale.md'
      - 'books/Mondstadt/Along_with_Divinity_Prologue.md'
      - 'books/Mondstadt/Ancient_Investigation_Journal.md'
      - 'books/Mondstadt/Ballads_of_the_Squire.md'
      - 'books/Mondstadt/Biography_of_Gunnhildr.md'
      - 'books/Mondstadt/Breeze_Amidst_the_Forest.md'
      - 'books/Mondstadt/Draft_Hilichurl_Ballads.md'
      - 'books/Mondstadt/Gliding_Instruction_Manual.md'
      - 'books/Mondstadt/Handy_Handbook_of_Hilichurlian.md'
      - 'books/Mondstadt/Heart_of_Clear_Springs.md'
      - 'books/Mondstadt/Hilichurl_Ballad_Selection.md'
      - 'books/Mondstadt/Hilichurl_Cultural_Customs.md'
      - 'books/Mondstadt/History_of_Kings_and_Clans_-_Prologue.md'
      - 'books/Mondstadt/Knights_of_Favonius_Handbook_-_5th_Edition.md'
      - 'books/Mondstadt/The_Boar_Princess.md'
      - 'books/Mondstadt/The_Fox_in_the_Dandelion_Sea.md'
      - 'books/Mondstadt/The_Legend_of_Vennessa.md'
      - 'books/Mondstadt/The_Mondstadt_Tower.md'
      - 'books/Mondstadt/The_Pale_Princess_and_the_Six_Pygmies.md'
      - 'books/Mondstadt/Veras_Melancholy.md'
      - 'books/Mondstadt/Wind_Courage_and_Wings.md'
    - 'Inazuma':
      - 'books/Inazuma/The_Byakuyakoku_Collection.md'
    - 'Fontaine':
      - 'books/Fontaine/Perinheri.md'
  - 'Notes':
    - 'notes/index.md'
    - 'Mondstadt':
      - 'notes/Mondstadt/Lost_Adventure_Notebook.md'
  - 'About': 'about.md'
markdown_extensions:
  - admonition
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wolf0905/genshin-lore-doc
repo_url: https://github.com/wolf0905/genshin-lore-doc
repo_name: genshin-lore-doc