site_name: Genshin Lore Docs
site_url: https://wolf0905.github.io/genshin-lore-doc/
theme:
  name: material
  custom_dir: overrides
  features:
   - navigation.tabs
   - navigation.tabs.sticky
   - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
nav:
  - 'Home': 'index.md'
  - 'Books':
    - 'books/index.md'
    - 'Mondstadt':
      - 'books/Mondstadt/Of_Mountains_and_Seas.md'
      - 'books/Mondstadt/1000_Years_of_Loneliness.md'
      - 'books/Mondstadt/A_Drunkards_Tale.md'
      - 'books/Mondstadt/Along_with_Divinity_Prologue.md'
      - 'books/Mondstadt/Ancient_Investigation_Journal.md'
      - 'books/Mondstadt/Ballads_of_the_Squire.md'
      - 'books/Mondstadt/Biography_of_Gunnhildr.md'
      - 'books/Mondstadt/Breeze_Amidst_the_Forest.md'
      - 'books/Mondstadt/Draft_Hilichurl_Ballads.md'
      - 'books/Mondstadt/Gliding_Instruction_Manual.md'
      - 'books/Mondstadt/Handy_Handbook_of_Hilichurlian.md'
      - 'books/Mondstadt/Heart_of_Clear_Springs.md'
      - 'books/Mondstadt/Hilichurl_Ballad_Selection.md'
      - 'books/Mondstadt/Hilichurl_Cultural_Customs.md'
      - 'books/Mondstadt/History_of_Kings_and_Clans_-_Prologue.md'
      - 'books/Mondstadt/Knights_of_Favonius_Handbook_-_5th_Edition.md'
      - 'books/Mondstadt/The_Boar_Princess.md'
      - 'books/Mondstadt/The_Fox_in_the_Dandelion_Sea.md'
      - 'books/Mondstadt/The_Legend_of_Vennessa.md'
      - 'books/Mondstadt/The_Mondstadt_Tower.md'
      - 'books/Mondstadt/The_Pale_Princess_and_the_Six_Pygmies.md'
      - 'books/Mondstadt/Veras_Melancholy.md'
      - 'books/Mondstadt/Wind_Courage_and_Wings.md'
    - 'Liyue':
      - 'books/Liyue/Customs_of_Liyue.md'
      - 'books/Liyue/Humor_From_Tianheng.md'
      - 'books/Liyue/Legend_of_the_Lone_Sword.md'
      - 'books/Liyue/Legend_of_the_Shattered_Halberd.md'
      - 'books/Liyue/Linling_Anthology.md'
      - 'books/Liyue/Meadow_of_Gems.md'
      - 'books/Liyue/Moonlit_Bamboo_Forest.md'
      - 'books/Liyue/Records_of_Jueyun.md'
      - 'books/Liyue/Records_of_the_Gallant.md'
      - 'books/Liyue/Rex_Incognito.md'
      - 'books/Liyue/Stone_Tablet_Compilations_-_Vol._I.md'
      - 'books/Liyue/String_of_Pearls.md'
      - 'books/Liyue/Tales_From_the_Waves.md'
      - 'books/Liyue/Verses_of_Equilibrium.md'
      - 'books/Liyue/Yakshas_The_Guardian_Adepti.md'
    - 'Inazuma':
      - 'books/Inazuma/The_Byakuyakoku_Collection.md'
      - 'books/Inazuma/A_Legend_of_Sword.md'
      - 'books/Inazuma/A_Preliminary_Study_of_Sangonomiya_Folk_Belief.md'
      - 'books/Inazuma/Debates_on_the_Viceroy_of_the_East.md'
      - 'books/Inazuma/Flowers_for_Princess_Fischl.md'
      - 'books/Inazuma/Lets_Go_Dodoco.md'
      - 'books/Inazuma/New_Chronicles_of_the_Six_Kitsune.md'
      - 'books/Inazuma/Onibudou.md'
    - 'Fontaine':
      - 'books/Fontaine/Perinheri.md'
  - 'Notes':
    - 'notes/index.md'
    - 'Mondstadt':
      - 'notes/Mondstadt/Lost_Adventure_Notebook.md'
  - 'About': 'about.md'
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wolf0905/genshin-lore-doc
repo_url: https://github.com/wolf0905/genshin-lore-doc
repo_name: genshin-lore-doc